### ISSUE TITLE
Create a new world and teleport to the new world will crash server

### ISSUE THREAD

**Issue by Happy-FZM** [GideonWhite1029/PurpurAsync#1]
Server Plugins: Multiverse-Core

Create a new world and teleport to the new world will crash server

```
[22:56:06 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread serverlevel-tick-worker [world] failed main thread check: Loading in poi chunk off-main @ world test chunkX: -4 chunkZ: -3 - Is tick thread? true; Is server level tick thread? true; Currently ticking level: world; Is iterating over levels? true; Are we going to hard throw? true
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:49) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.poi.PoiChunk.load(PoiChunk.java:52) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:54) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:788) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:340) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:378) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:399) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:345) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:779) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$19(MinecraftServer.java:1849) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:56:06 ERROR]: [ChunkTaskScheduler] Chunk system error at chunk (-4,-3), holder: NewChunkHolder{world=test, chunkX=-4, chunkZ=-3, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=net.minecraft.world.level.chunk.ProtoChunk,status=minecraft:spawn}, currentGenStatus=minecraft:spawn, requestedGenStatus=minecraft:full, generationTask=ChunkProgressionTask{class: ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask, for world: test, chunk: (-4,-3), hashcode: 296571884, priority: COMPLETING, status: minecraft:full, scheduled: true}, generationTaskStatus=minecraft:full, priority=null, priorityLocked=false, neighbourRequestedPriority=null, effective_priority=null, oldTicketLevel=33, currentTicketLevel=33, totalNeighboursUsingThisChunk=41, fullNeighbourChunksLoadedBitset=32399872, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}, exception:
java.lang.Throwable: java.lang.IllegalStateException: Loading in poi chunk off-main
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:336) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1622) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete0(ChunkProgressionTask.java:91) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete(ChunkProgressionTask.java:74) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:85) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:788) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:340) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:378) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:399) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:345) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:779) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$19(MinecraftServer.java:1849) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Loading in poi chunk off-main
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.poi.PoiChunk.load(PoiChunk.java:52) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:54) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        ... 17 more
[22:56:06 ERROR]: Negative index in crash report handler (20/22)
[22:56:06 ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Chunk system crash propagated to tick()
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1352) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:336) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Chunk system crash propagated from unrecoverableChunkSystemFailure
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:365) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1622) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete0(ChunkProgressionTask.java:91) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete(ChunkProgressionTask.java:74) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:85) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:788) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:340) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:378) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:399) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:345) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:779) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$19(MinecraftServer.java:1849) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
Caused by: net.minecraft.ReportedException: Chunk system error
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:342) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1622) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete0(ChunkProgressionTask.java:91) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkProgressionTask.complete(ChunkProgressionTask.java:74) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:85) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:788) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:340) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:378) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:399) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:345) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:779) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$19(MinecraftServer.java:1849) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
Caused by: java.lang.IllegalStateException: Loading in poi chunk off-main
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.poi.PoiChunk.load(PoiChunk.java:52) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:54) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:788) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:340) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:378) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:399) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:345) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:779) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$19(MinecraftServer.java:1849) ~[purpurasync-1.21.1.jar:1.21.1-DEV-6823c53]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
```

**Comment by GideonWhite1029** [comment]
@Happy-FZM Which version are you using?

**Comment by Happy-FZM** [comment]
> @Happy-FZM Which version are you using?

   Server name: PurpurAsync
   Version: 1.21.1-DEV-6823c53 (MC: 1.21.1)
   API version: 1.21.1-R0.1-SNAPSHOT
   Github commit: 6823c53

**Comment by GideonWhite1029** [comment]
> > @Happy-FZM Which version are you using?
> 
> Server name: PurpurAsync Version: 1.21.1-DEV-6823c53 (MC: 1.21.1) API version: 1.21.1-R0.1-SNAPSHOT Github commit: [6823c53](https://github.com/GideonWhite1029/PurpurAsync/commit/6823c539b509bfb89b4ed95938afa2b39df9fe2c)

This version is not ready for use and I am still rewriting the patch for parallel worlds

**Comment by Happy-FZM** [comment]
> > > @Happy-FZM Which version are you using?
> > 
> > 
> > Server name: PurpurAsync Version: 1.21.1-DEV-6823c53 (MC: 1.21.1) API version: 1.21.1-R0.1-SNAPSHOT Github commit: [6823c53](https://github.com/GideonWhite1029/PurpurAsync/commit/6823c539b509bfb89b4ed95938afa2b39df9fe2c)
> 
> This version is not ready for use and I am still rewriting the patch for parallel worlds

Okay but I think this bug maybe caused by some patches upstream (Purpur), I tried to switch the upstream back to Paper it did not reproduce this bug

**Comment by GideonWhite1029** [comment]
> > > > @Happy-FZM Which version are you using?
> > > 
> > > 
> > > Server name: PurpurAsync Version: 1.21.1-DEV-6823c53 (MC: 1.21.1) API version: 1.21.1-R0.1-SNAPSHOT Github commit: [6823c53](https://github.com/GideonWhite1029/PurpurAsync/commit/6823c539b509bfb89b4ed95938afa2b39df9fe2c)
> > 
> > 
> > This version is not ready for use and I am still rewriting the patch for parallel worlds
> 
> Okay but I think this bug maybe caused by some patches upstream (Purpur), I tried to switch the upstream back to Paper it did not reproduce this bug

I have the same assumptions, I will find out where the problem is.

**Comment by Happy-FZM** [comment]
> > > > > @Happy-FZM Which version are you using?
> > > > 
> > > > 
> > > > Server name: PurpurAsync Version: 1.21.1-DEV-6823c53 (MC: 1.21.1) API version: 1.21.1-R0.1-SNAPSHOT Github commit: [6823c53](https://github.com/GideonWhite1029/PurpurAsync/commit/6823c539b509bfb89b4ed95938afa2b39df9fe2c)
> > > 
> > > 
> > > This version is not ready for use and I am still rewriting the patch for parallel worlds
> > 
> > 
> > Okay but I think this bug maybe caused by some patches upstream (Purpur), I tried to switch the upstream back to Paper it did not reproduce this bug
> 
> I have the same assumptions, I will find out where the problem is.

Great!

**Comment by GideonWhite1029** [comment]
One of the Purpur patches radically changes the way chunks work, so maybe I'll switch to a patch from another fork: https://github.com/CraftCanvasMC/Canvas/blob/master/patches/server/0048-Multithreaded-Ticking.patch

**Comment by Happy-FZM** [comment]
> One of the Purpur patches radically changes the way chunks work, so maybe I'll switch to a patch from another fork: https://github.com/CraftCanvasMC/Canvas/blob/master/patches/server/0048-Multithreaded-Ticking.patch

The patch looks good
